#!/bin/bash

# run in your working directory or set a path to files generated by script 01_extract_transcripts_for_introns.R

awk -F "\t" '{split($4,a,"_") ; print $1"\t"$2"\t"$3"\t"a[1]"\t"$4"\t"$5"\t"$6}' biomart_transcript_ids_introns.bed > biomart_transcript_ids_introns_1.bed
join -1 4 -2 6 -o 1.1 1.2 1.3 1.5 2.5 1.6 1.7 1.8 -t $'\t' <(sort -k4 biomart_transcript_ids_introns_1.bed ) <(sort -k6 biomart_transcript_ids_position.txt) > biomart_transcript_ids_introns_sorted.bed

mkdir brain_samples
mkdir brain_samples/average_cov_bin
mkdir LXL_introns_bed